version: '3'

services:
  redis_netapp:
    image: redis:latest
    container_name: redis_netapp
    networks:
      - demo-network
  python_netapp:
    image: python_netapp
    networks:
      - demo-network
    hostname: dummy
    container_name: python_netapp
    build:
      context: ./pythonnetapp
    volumes:
      - ./pythonnetapp:/usr/src/app
    environment:
      - REDIS_HOST=redis_netapp
      - REDIS_PORT=6379
      - PATH_TO_CERTS=/usr/src/app/capif_onboarding
      - CAPIF_HOSTNAME=capifcore
      - CAPIF_PORT_HTTP=8080
      - CAPIF_PORT_HTTPS=443
      - CAPIF_CALLBACK_URL=host.docker.internal
      - CAPIF_CALLBACK_PORT=8086
      - NEF_USER=admin@my-email.com
      - NEF_PASS=pass
      - NEF_IP=host.docker.internal
      - NEF_PORT=8888
      - NEF_CALLBACK_IP=host.docker.internal
      - NEF_CALLBACK_PORT=8085
    depends_on:
      - redis_netapp
    extra_hosts:
      - host.docker.internal:host-gateway
      - capifcore:host-gateway
  nef_callback_server:
     build:
       context: ./nef_callback_server
     networks:
       - demo-network
     ports:
       - 8085:8080
     volumes:
       - ./nef_callback_server:/usr/src/app
     environment:
       - REDIS_HOST=redis_netapp
       - REDIS_PORT=6379
     depends_on:
       - redis_netapp
     extra_hosts:
       - host.docker.internal:host-gateway
  capif_callback_netapp:
     build:
       context: ./capif_callback_netapp
     networks:
       - demo-network
     ports:
       - 8086:8080
     volumes:
       - ./capif_callback_netapp:/usr/src/app
     environment:
       - REDIS_HOST=redis_netapp
       - REDIS_PORT=6379
     depends_on:
       - redis_netapp
     extra_hosts:
       - host.docker.internal:host-gateway

networks:
  demo-network:
    external: true